displayName=Player Tracker
author=Epuuc
description=Track all the players in an area, giving you a total number, as well as keeping a list of players you run into during your session.
tags=players,tracking
version=1.0.0
plugins=com.PlayerTracker.PlayerTrackerPlugin
build=standard